api/urls.py
from django.urls import path
from .views import CardApiView,OneCardApiView
from .student_api import StudentApiListView,StudentDetailApiView,StudentUpdateApiView,StudentCreateApiView



urlpatterns = [
    path('cards/', CardApiView.as_view(), name='cards'),
    path('one-card/', OneCardApiView.as_view(), name='one_card'),
    path('create-card/', CardApiView.as_view(), name='create_card'),

    # student api views

    path('student-api/', StudentApiListView.as_view(), name='student_api'),
    path('student-detail/<int:id>/', StudentDetailApiView.as_view(), name='student_detail'),
    path('student-update/<int:id>/', StudentUpdateApiView.as_view(), name='student_update'),
    path('student-create/', StudentCreateApiView.as_view(), name='student_create'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('students.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

students/urls.py
from django.urls import path
from .views import StudentsListView,StudentDetailView,StudentUpdateView


app_name = "students"

urlpatterns = [
    path('list/', StudentsListView.as_view(), name='list'),
    path('detail/<int:id>/', StudentDetailView.as_view(), name='detail'),
    path('update/<int:id>/', StudentUpdateView.as_view(), name='update'),
]

api/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


HUMO , UZCARD , VISA = 'uzcard','humo','visa'


class User(AbstractUser):
    photo = models.ImageField(upload_to='users_photo/' , default='users_photo/default.png')
    phone_number = models.CharField(max_length=13, blank=True, null=True, unique=True)

    def __str__(self):
        return f"{self.username}"


class Card(models.Model):
    CARD_TYPE_CHOICES = (
        (HUMO, 'HUMO'),
        (UZCARD, 'UZCARD'),
        (VISA, 'VISA'),
    )

    card_number = models.CharField(max_length=16,unique=True,db_index=True)
    valid_time = models.CharField(max_length=4)
    card_type = models.CharField(max_length=20)
    bank_name = models.CharField(max_length=50)
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='cards')


    def __str__(self):
        return f"{self.name} : {self.card_number}"

students/models.py
from django.db import models

class Student(models.Model):
    frist_name = models.CharField(max_length=125)
    last_name = models.CharField(max_length=125)
    email = models.EmailField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"{self.frist_name} {self.last_name}"

students/forms.py
from django import forms
from .models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        exclude = ['id']
        # fields = ('frist_name', 'last_name', 'email')

api/views.py
from django.shortcuts import render
from .models import Card
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import CardSerializer
from django.shortcuts import get_object_or_404



class CardApiView(APIView):
    def get(self, request):
        cards = Card.objects.all()
        serializer = CardSerializer(cards, many=True)   
        return Response(serializer.data)
    

class OneCardApiView(APIView):
    def post(self, request):
        if "card_number" not in request.data:
            data = {
                "status": False,
                "message": "card_number is required"

            }

            return Response(data)
        

        card_number = request.data["card_number"]
        card = get_object_or_404(Card, card_number=card_number)

    
        serializer = CardSerializer(card)
        return Response(serializer.data)
    


class CreateCardView(APIView):
    def post(self, request):
        serializer = CardSerializer(data=request.data)
        return Response(serializer.errors, status=400)
    

students/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import View
from .models import Student
from .forms import StudentForm


class StudentsListView(View):
    def get(self, request):
        students = Student.objects.all()

        data = {
            "students": students 
        }
        return render(request,'students/list.html',context=data)
    

class StudentDetailView(View):
    def get(self, request,id):
        student = get_object_or_404(Student,id=id)
        form = StudentForm(instance=student)
        data = {
            "form": form ,
            "student": student
        }

        return render(request,'students/detail.html',context=data)


class StudentUpdateView(View):
    def post(self, request,id):
        student = get_object_or_404(Student,id=id)

        form = StudentForm(request.POST,instance=student)
        if form.is_valid():
            form.save()
            return redirect('students:list')
        

        return render(request,'students/detail.html', context={"form":form})

students/templates/students/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container">    <table class="table">
        
        <form action="{% url 'students:update' student.id %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-outline-info">Update</button>
        </form>
       
      </table></div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>

students/templates/students/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container">    <table class="table">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Email</th>
            <th scope="col">Buttons</th>
          </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <th scope="row">{{ student.id }}</th>
                <td>{{ student.frist_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                <td><a href="{% url 'students:detail' student.id %}" class="btn btn-outline-primary">Detail</a></td>
              </tr>
            {% endfor %}
        </tbody>
      </table></div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>